version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: distribuidos_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: netapp_db
      MYSQL_USER: erick
      MYSQL_PASSWORD: erickpass
    ports:
      - "3307:3306"
    volumes:
      - ./init:/docker-entrypoint-initdb.d
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
